sudo: required
dist: trusty

language: haxe

haxe:
  - "4.1.3"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - haxelib dev hxobfuscator .
  - haxe build.hxml
  - haxe test.hxml

notifications:
  email: false
